package com.example.jiehe.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.qimojineng03.Foods;

import com.example.jiehe.dao.FoodsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodsDaoConfig;

    private final FoodsDao foodsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodsDaoConfig = daoConfigMap.get(FoodsDao.class).clone();
        foodsDaoConfig.initIdentityScope(type);

        foodsDao = new FoodsDao(foodsDaoConfig, this);

        registerDao(Foods.class, foodsDao);
    }
    
    public void clear() {
        foodsDaoConfig.clearIdentityScope();
    }

    public FoodsDao getFoodsDao() {
        return foodsDao;
    }

}
