package com.example.qimojinengd.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import bean.Daobean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DAOBEAN".
*/
public class DaobeanDao extends AbstractDao<Daobean, Long> {

    public static final String TABLENAME = "DAOBEAN";

    /**
     * Properties of entity Daobean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "Id", true, "_id");
        public final static Property Desc = new Property(1, String.class, "Desc", false, "DESC");
        public final static Property EnvelopePic = new Property(2, String.class, "EnvelopePic", false, "ENVELOPE_PIC");
    }


    public DaobeanDao(DaoConfig config) {
        super(config);
    }
    
    public DaobeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DAOBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: Id
                "\"DESC\" TEXT," + // 1: Desc
                "\"ENVELOPE_PIC\" TEXT);"); // 2: EnvelopePic
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DAOBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Daobean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String Desc = entity.getDesc();
        if (Desc != null) {
            stmt.bindString(2, Desc);
        }
 
        String EnvelopePic = entity.getEnvelopePic();
        if (EnvelopePic != null) {
            stmt.bindString(3, EnvelopePic);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Daobean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String Desc = entity.getDesc();
        if (Desc != null) {
            stmt.bindString(2, Desc);
        }
 
        String EnvelopePic = entity.getEnvelopePic();
        if (EnvelopePic != null) {
            stmt.bindString(3, EnvelopePic);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Daobean readEntity(Cursor cursor, int offset) {
        Daobean entity = new Daobean( //
            cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Desc
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // EnvelopePic
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Daobean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setDesc(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEnvelopePic(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Daobean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Daobean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Daobean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
