package com.example.jiehe.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.lianxi1234.Foods;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FOODS".
*/
public class FoodsDao extends AbstractDao<Foods, Void> {

    public static final String TABLENAME = "FOODS";

    /**
     * Properties of entity Foods.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Pic = new Property(0, String.class, "pic", false, "PIC");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
    }


    public FoodsDao(DaoConfig config) {
        super(config);
    }
    
    public FoodsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FOODS\" (" + //
                "\"PIC\" TEXT," + // 0: pic
                "\"TITLE\" TEXT);"); // 1: title
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FOODS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Foods entity) {
        stmt.clearBindings();
 
        String pic = entity.getPic();
        if (pic != null) {
            stmt.bindString(1, pic);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Foods entity) {
        stmt.clearBindings();
 
        String pic = entity.getPic();
        if (pic != null) {
            stmt.bindString(1, pic);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Foods readEntity(Cursor cursor, int offset) {
        Foods entity = new Foods( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // pic
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // title
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Foods entity, int offset) {
        entity.setPic(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Foods entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Foods entity) {
        return null;
    }

    @Override
    public boolean hasKey(Foods entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
